[build]
  functions = "netlify/functions"
  command = "echo Building Functions"

[functions]
  external_node_modules = ["express", "qrcode", "cors"]
  node_bundler = "esbuild"

# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200
#   force = true
