[build]
functions = "netlify/functions"
command = "echo Building Functions"

# [functions]
# external_node_modules = ["qrcode"]
# node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/qr"
status = 200
force = true
